# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - stopwatch-tasks

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: FTP Deploy
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@da0d77ff390a13097c60f9b9eb954e503a480d97
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        ftp-server: files.000webhost.com/public_html
        # FTP account username
        ftp-username: stopwatch-tasks
        # FTP account password
        ftp-password: ${{ secrets.FTP_PASSWORD_000_WEBHOST_STOPWATCHTASK }}
        # The local folder to copy, defaults to root project folder
        local-dir: build/ # optional, default is ./
        # Passes through options into git-ftp
        # git-ftp-args: # optional
